/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_howell_jni_JniUtil */

#ifndef _Included_com_howell_jni_JniUtil
#define _Included_com_howell_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeInit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeRenderY
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeRenderY
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeRenderU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeRenderU
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeRenderV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeRenderV
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeOnSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeOnSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeAudioInit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeAudioInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeAudioDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeAudioDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeAudioStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeAudioStop
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    downloadInitEx
 * Signature: (Ljava/lang/Object;Ljava/lang/String;ISSSSSSSSSSSS)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_downloadInitEx
  (JNIEnv *, jclass, jobject, jstring, jint, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    downloadDestoryEx
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_downloadDestoryEx
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    downloadInit
 * Signature: (Ljava/lang/Object;ILjava/lang/String;ISSSSSSSSSSSS)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_downloadInit
  (JNIEnv *, jclass, jobject, jint, jstring, jint, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    downloadDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_downloadDestory
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    cameraLogin
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_cameraLogin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    display
 * Signature: (IISSSSSSSSSSSS)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_display
  (JNIEnv *, jclass, jint, jint, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_quit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    changeToD1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_changeToD1
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    changeTo720P
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_changeTo720P
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    getReplayListCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_getReplayListCount
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    catchPicture
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_catchPicture
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    setFlip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_setFlip
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    getStreamLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_getStreamLen
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    playbackPause
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_playbackPause
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    playBackPositionChange
 * Signature: (SSSSSSSSSSSS)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_playBackPositionChange
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    ptzTurnLeft
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_ptzTurnLeft
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    ptzTurnRight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_ptzTurnRight
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    ptzTurnUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_ptzTurnUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    ptzTurnDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_ptzTurnDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    zoomTele
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_zoomTele
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    zoomWide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_zoomWide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    getWifi
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_getWifi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    setWifi
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_setWifi
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    getReplayList
 * Signature: (II)[Lcom/howell/ecameraap/ReplayFile;
 */
JNIEXPORT jobjectArray JNICALL Java_com_howell_jni_JniUtil_getReplayList
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    closeFileList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_closeFileList
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    getListByPage
 * Signature: (IIILcom/howell/ecameraap/ReplayFile;IILcom/howell/ecameraap/Pagination;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_getListByPage
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint, jobject);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    vedioListLogin
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_vedioListLogin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    vedioListLogout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_vedioListLogout
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    displayLocalFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_displayLocalFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    localFileQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_localFileQuit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
